[2019-10-03 16:50:23,051] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_port_code_staging_table 2019-10-03T21:39:04.779948+00:00 [queued]>
[2019-10-03 16:50:23,078] {taskinstance.py:620} INFO - Dependencies all met for <TaskInstance: capstone_project_dag.Load_port_code_staging_table 2019-10-03T21:39:04.779948+00:00 [queued]>
[2019-10-03 16:50:23,078] {taskinstance.py:838} INFO - 
--------------------------------------------------------------------------------
[2019-10-03 16:50:23,078] {taskinstance.py:839} INFO - Starting attempt 3 of 4
[2019-10-03 16:50:23,078] {taskinstance.py:840} INFO - 
--------------------------------------------------------------------------------
[2019-10-03 16:50:23,090] {taskinstance.py:859} INFO - Executing <Task(CsvCopyS3ToRedshiftOperator): Load_port_code_staging_table> on 2019-10-03T21:39:04.779948+00:00
[2019-10-03 16:50:23,090] {base_task_runner.py:133} INFO - Running: ['airflow', 'run', 'capstone_project_dag', 'Load_port_code_staging_table', '2019-10-03T21:39:04.779948+00:00', '--job_id', '320', '--pool', 'default_pool', '--raw', '-sd', 'DAGS_FOLDER/project_dag.py', '--cfg_path', '/var/folders/dr/9yvjlnm11xv25k2gknf2n3z00000gn/T/tmpc0423uva']
[2019-10-03 16:50:23,574] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table /usr/local/lib/python3.7/site-packages/airflow/configuration.py:627: DeprecationWarning: You have two airflow.cfg files: /Users/victorialemay/airflow/airflow.cfg and /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg. Airflow used to look at ~/airflow/airflow.cfg, even when AIRFLOW_HOME was set to a different value. Airflow will now only read /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/airflow.cfg, and you should remove the other file
[2019-10-03 16:50:23,575] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   category=DeprecationWarning,
[2019-10-03 16:50:23,664] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table [2019-10-03 16:50:23,664] {settings.py:213} INFO - settings.configure_orm(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=8563
[2019-10-03 16:50:23,856] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table [2019-10-03 16:50:23,855] {__init__.py:51} INFO - Using executor LocalExecutor
[2019-10-03 16:50:24,262] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table [2019-10-03 16:50:24,262] {dagbag.py:90} INFO - Filling up the DagBag from /Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/dags/project_dag.py
[2019-10-03 16:50:24,298] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table [2019-10-03 16:50:24,298] {cli.py:516} INFO - Running <TaskInstance: capstone_project_dag.Load_port_code_staging_table 2019-10-03T21:39:04.779948+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2019-10-03 16:50:24,326] {csv_copy_s3_to_redshift.py:35} INFO - Using CSV data file port_codes.csv from S3 bucket project-capstone
[2019-10-03 16:50:24,326] {csv_copy_s3_to_redshift.py:36} INFO - Inserting into destination Redshift table port_code_staging
[2019-10-03 16:50:24,350] {csv_copy_s3_to_redshift.py:42} INFO - Copying data from S3 to Redshift
[2019-10-03 16:50:24,361] {logging_mixin.py:95} INFO - [[34m2019-10-03 16:50:24,361[0m] {[34mbase_hook.py:[0m84} INFO[0m - Using connection to: [1mid: redshift. Host: redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com, Port: 5439, Schema: dev, Login: awsuser, Password: XXXXXXXX, extra: {}[0m[0m
[2019-10-03 16:50:24,479] {taskinstance.py:1051} ERROR - could not connect to server: Connection refused
	Is the server running on host "redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com" (100.20.213.146) and accepting
	TCP/IP connections on port 5439?
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/csv_copy_s3_to_redshift.py", line 52, in execute
    redshift.run(formatted_sql)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com" (100.20.213.146) and accepting
	TCP/IP connections on port 5439?

[2019-10-03 16:50:24,485] {taskinstance.py:1074} INFO - Marking task as UP_FOR_RETRY
[2019-10-03 16:50:24,507] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table Traceback (most recent call last):
[2019-10-03 16:50:24,507] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/bin/airflow", line 32, in <module>
[2019-10-03 16:50:24,507] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     args.func(args)
[2019-10-03 16:50:24,507] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-10-03 16:50:24,507] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     return f(*args, **kwargs)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 522, in run
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     _run(args, dag, ti)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 440, in _run
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     pool=args.pool,
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     return func(*args, **kwargs)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 926, in _run_raw_task
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     result = task_copy.execute(context=context)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/Users/victorialemay/Courses/Udacity/Data Engineering Nanodegree/capstone/project-archive/airflow/plugins/operators/csv_copy_s3_to_redshift.py", line 52, in execute
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     redshift.run(formatted_sql)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 159, in run
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     with closing(self.get_conn()) as conn:
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 75, in get_conn
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     self.conn = psycopg2.connect(**conn_args)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table   File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[2019-10-03 16:50:24,508] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table psycopg2.OperationalError: could not connect to server: Connection refused
[2019-10-03 16:50:24,509] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table 	Is the server running on host "redshift-cluster-1.c4i0rfzboubh.us-west-2.redshift.amazonaws.com" (100.20.213.146) and accepting
[2019-10-03 16:50:24,509] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table 	TCP/IP connections on port 5439?
[2019-10-03 16:50:24,509] {base_task_runner.py:115} INFO - Job 320: Subtask Load_port_code_staging_table 
[2019-10-03 16:50:28,023] {logging_mixin.py:95} INFO - [[34m2019-10-03 16:50:28,023[0m] {[34mlocal_task_job.py:[0m105} INFO[0m - Task exited with return code 1[0m
